package Interface;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import Entities.User;
import Models.UserModel;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class Inscription extends JFrame {

    /**
     * Creates new form Inscription
     */
    public Inscription() {
        initComponents();
        setSize(400,400);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tp_confirmationMdp = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tp_nom = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tp_prenom = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tp_email = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tp_mdp = new javax.swing.JTextPane();
        button_inscription = new javax.swing.JButton();
        button_inscription.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		String nom = tp_nom.getText().toString();
        		String mdp = tp_mdp.getText().toString();
        		String prenom = tp_prenom.getText().toString();
        		String email = tp_email.getText().toString();
        		
        		
        		int id = 0;
        		
        		UserModel UserModele = new UserModel();
                List<User> listUser = new ArrayList<>();
                listUser = UserModele.getAllUsers();
                try {
					id = UserModele.maxID();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
                int i = 0;
                String nom1 = listUser.get(i).getNom().toString();
                String prenom1 = listUser.get(i).getPrenom().toString();
               
                while((i<listUser.size())&&(!nom1.equals(nom)) && (!prenom1.equals(prenom)))
                {
                	nom1 = listUser.get(i).getNom().toString();
                	prenom1 = listUser.get(i).getPrenom().toString();
                	i++;
                }
                if(i==listUser.size())
                {
                	User user = new User(id,nom,prenom,email,mdp,LocalDateTime.now());
                	javax.swing.JOptionPane.showMessageDialog(null," Inscription réussi");
                	UserModele.addUser(user);
                	setVisible(false);
                }else
                {
                	javax.swing.JOptionPane.showMessageDialog(null,"Ce nom et prenom existe déja !");
                }
                
        	}
        });
        button_annuler = new javax.swing.JButton();
        button_annuler.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		setVisible(false);
        	}
        });
        label_confirmationMdp = new javax.swing.JLabel();
        label_nom = new javax.swing.JLabel();
        label_prenom = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_mdp = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(tp_confirmationMdp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 80, -1));

        jScrollPane2.setViewportView(tp_nom);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 80, -1));

        jScrollPane3.setViewportView(tp_prenom);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 80, -1));

        jScrollPane4.setViewportView(tp_email);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 80, -1));

        jScrollPane5.setViewportView(tp_mdp);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 80, -1));

        button_inscription.setText("Je m'inscris");
        getContentPane().add(button_inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        button_annuler.setText("Annuler");
        getContentPane().add(button_annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        label_confirmationMdp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_confirmationMdp.setText("Confirmer le mot de passe :");
        getContentPane().add(label_confirmationMdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 20));

        label_nom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_nom.setText("Nom :");
        getContentPane().add(label_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 40, 20));

        label_prenom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_prenom.setText("Prénom :");
        getContentPane().add(label_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 50, 20));

        label_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_email.setText("Email : ");
        getContentPane().add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 100, 40, 20));

        label_mdp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_mdp.setText("Mot de passe :");
        getContentPane().add(label_mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_annuler;
    private javax.swing.JButton button_inscription;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel label_confirmationMdp;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_mdp;
    private javax.swing.JLabel label_nom;
    private javax.swing.JLabel label_prenom;
    private javax.swing.JTextPane tp_confirmationMdp;
    private javax.swing.JTextPane tp_email;
    private javax.swing.JTextPane tp_mdp;
    private javax.swing.JTextPane tp_nom;
    private javax.swing.JTextPane tp_prenom;
    // End of variables declaration//GEN-END:variables
}
