package Interface;
import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import Entities.User;
import Models.UserModel;
import Utils.Session;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

public class Login extends JFrame  {

	
	
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(375,350);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp_login = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tp_mdp = new javax.swing.JTextPane();
        button_connexion = new javax.swing.JButton();
        Session sess = Session.getInstance();
        button_connexion.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		String nom = tp_login.getText().toString();
        		String mdp = tp_mdp.getText().toString();
        		int i = 0;
        		UserModel UserModele = new UserModel();
        		User us = new User();
        		us = UserModele.getUserbyNamePassword(nom, mdp);
        		System.out.println(us.getNom());
        		if(us.getNom() == null)
        		{
        			javax.swing.JOptionPane.showMessageDialog(null,"Connexion impossible, veuillez verifier votre identifiant ou mot de passe ! ");
        		}else
        		{
        			javax.swing.JOptionPane.showMessageDialog(null,"Connexion réussi "+ nom + " " + us.getNom()+ " "+  us.getPrenom() );
               
                	
                	sess.us = us;
                	
                	setVisible(false);
                 	Main main = new Main();
                	main.setVisible(true);
                	
        		}
              
        	}
        });
        tf_inscription = new javax.swing.JTextField();
        lblMotDePasse = new javax.swing.JLabel();
        label_nom = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Titre.setForeground(new java.awt.Color(200, 0, 0));
        Titre.setText("Gestion des finances");
        Titre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitreActionPerformed(evt);
            }
        });
        getContentPane().add(Titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jScrollPane1.setViewportView(tp_login);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 60, -1));

        jScrollPane2.setViewportView(tp_mdp);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 60, -1));

        button_connexion.setText("conexion");
        getContentPane().add(button_connexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        tf_inscription.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tf_inscription.setForeground(new java.awt.Color(0, 0, 255));
        tf_inscription.setText("Nouvel utilisateur ? Veuillez vous inscrire ICI");
        tf_inscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_inscriptionMouseClicked(evt);
            }
        });
        tf_inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_inscriptionActionPerformed(evt);
            }
        });
        getContentPane().add(tf_inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        lblMotDePasse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMotDePasse.setText("Mdp  :");
        getContentPane().add(lblMotDePasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        label_nom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_nom.setText("Nom :");
        getContentPane().add(label_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitreActionPerformed

    private void tf_inscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_inscriptionMouseClicked
        // redirection sur la page d'inscription
        Inscription inscription = new Inscription();
        inscription.setVisible(true);
        
    }//GEN-LAST:event_tf_inscriptionMouseClicked

    private void tf_inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_inscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_inscriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Titre;
    private javax.swing.JButton button_connexion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_nom;
    private javax.swing.JLabel lblMotDePasse;
    private javax.swing.JTextField tf_inscription;
    private javax.swing.JTextPane tp_login;
    private javax.swing.JTextPane tp_mdp;
    // End of variables declaration//GEN-END:variables
}